### ISSUE TITLE
parameter sharing

### ISSUE THREAD

**Issue by yinjiangjin** [murtazarang/MD-MADDPG#1]
Hi murtazarang, thanks a lot for sharing this MD-MADDPG's implementation. I'd like to ask you for some details about the code. I hope you can answer my doubts.

1.  I think that all agents share the same **actor and critic** network (including their target networks), is it?

2. When training the **actor network**, you use the **target_input** (i.e. input obs_next )  ( p_loss = self.p_train(*(target_input[self.agent_index] + act_n)) ). Why input the **obs_next** instead of **obs**?

**Comment by murtazarang** [comment]
Yep. I used parameter sharing to ease training. I see that there are changes made to the paper in its final submission, and one of layers, if remember correctly, use different layers. I'll make updates accordingly, later this weekend.

For part 2, if you take a look at the actor-critic model for DDPG, the target network use the obs_next, for making updates to the policy network.
